### ISSUE TITLE
Discuss parameter sweep

### ISSUE THREAD

**Issue by grantaguinaldo** [ssie-projects/ssie523-abm-markets#1]
I've included the details on this readme file.

https://github.com/ssie-projects/ssie523-abm-markets/blob/lux-abm/research/param-opt/README.md

**Comment by dcline1** [comment]
My code/model is MarketABM.ipynb on the develop branch, not LuxABM.ipynb. As I mentioned in my email on Monday, I’ve made material changes to the Lux model, so I created a new notebook for the new model which includes switching between fundamentalists and noise traders. I also cleaned up the implementation so that it can be called over and over again and return the same results. It doesn’t look like any of those changes made it into Christian’s code.

I also suggested we sweep over:
0 <  nu1 <  1
0 <= nu2 <= 0.05
1 <= Tc  <= 30

which I also implemented in my notebook, albeit at low resolution and without a loss function. I don’t think we need to sweep Tf and large values of b (and Tf) will make the model unstable because of numerical errors from forward Euler when using daily timesteps.

I also don't see a random seed being set anywhere in the py script used for generating your results. If the random seed is not reset to the same starting value for each set of parameters, the results will not be reproducible. The random seed is properly reset for each parameter set in MarketABM.ipynb, so all results in that notebook are reproducible.

**Comment by grantaguinaldo** [comment]
Looking at the dans new notebook it seems that everything is done, including parameter optimization. I’ll only work on the final write up with the results from Dan’s notebook.

**Comment by grantaguinaldo** [comment]
Added a folder ([simulation-results](https://github.com/ssie-projects/ssie523-abm-markets/tree/develop/research/simulation-results)) to the develop branch that has the parameter optimization. 

The set of parameters with the lowest mean square error between the model and the ground truth was 
`tc = 25.000000 nu1 = 0.700000 and nu2 =  0.005000`.

@clemp can you look format the charts at the end of [this notebook ](https://github.com/ssie-projects/ssie523-abm-markets/blob/develop/research/simulation-results/MarketABM-gta-param-opt.ipynb)so that I can included them in the final paper? These charts include the results from the ground truth, GBM and the model. Not sure what is the best way to display the data. Any insight to what maybe happening at the end of the simulation is also helpful.
